
- name: installing the cephadm cli mode
  shell: sudo cephadm add-repo --release pacific

- name: installing the ceph-common
  shell: sudo cephadm install ceph-common

- name: start docker container service
  service:
    name: docker
    state: restarted

- name: including the auth host task
  include_tasks: auth_hosts.yml

- name: including the cluster_creation task
  include_tasks: cluster_creating.yml

- name: including the labeling_nodes task
  include_tasks: labeling_nodes.yml
