- block: 
    - name: addding the monitor host in the cluster
      shell: sudo ceph orch host add ceph-mon

    - name: addding the osd1 host in the cluster
      shell: sudo ceph orch host add ceph-osd1

    - name: addding the osd2 host in the cluster
      shell: sudo ceph orch host add ceph-osd2

    - name: addding the mds host in the cluster
      shell: sudo ceph orch host add ceph-mds
  ignore_erros: true
