
- name: download the cephadm package
  get_url:
    url: https://github.com/ceph/ceph/raw/pacific/src/cephadm/cephadm
    dest: /usr/bin/

- name: the permisstion to exicutable
  file:
    dest: /usr/bin/cephadm
    mode: 'a+x'

- name: run the bootstrape command
  shell: sudo cephadm bootstrap --mon-ip {{ ansible_default_ipv4.address }} --allow-overwrite 
  register: result_out
  retries: 2
  delay: 2

- name: debug
  debug:
    var: result_out.stderr_lines

- name: Include vars of  
  include_vars:
    file: lvm.yml

- name: including the adding host task
  include_tasks: adding_hosts.yml
