
- name: download the cephadm package
  get_url:
    url: https://github.com/ceph/ceph/raw/pacific/src/cephadm/cephadm
    dest: /usr/bin/

- name: the permisstion to exicutable
  file:
    dest: /usr/bin/cephadm
    mode: 'a+x'

- name: run the bootstrape command
  command: cephadm bootstrap --mon-ip {{ ansible_default_ipv4.address }} --allow-overwrite 
  register: result
  ignore_errors: yes

- name: run the bootstarap agian
  shell: systemctl stop ceph.target
  when: result.rc == '1'

- name: run the bootstrape command
  shell: cephadm bootstrap --mon-ip {{ ansible_default_ipv4.address }} --allow-overwrite 
  register: result_out
  retries: 2
  delay: 2
  ignore_errors: True

- name: debug
  debug:
    var: result_out.stderr_lines

- name: get the key from /etc/ceph/ceph.conf for enable the ceph-cli
  shell: cat /etc/ceph/ceph.conf | grep 'fsid' | awk '{print $3}' FS=' '
  register: keyid

- debug: var=keyid.stdout

- name: enable the ceph-cli mode
  command: "/usr/bin/cephadm shell --fsid {{ keyid.stdout }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring"

- name: installing the cephadm cli mode
  shell: cephadm add-repo --release pacific

- name: installing the ceph-common
  shell: cephadm install ceph-common

- name: start docker container service
  service:
    name: docker
    state: restarted
    
- name: Set authorized key in monitor node
  shell: ssh-copy-id -f -i /etc/ceph/ceph.pub root@ceph-mon

- name: Set authorized key in osd1 node
  shell: ssh-copy-id -f -i /etc/ceph/ceph.pub root@ceph-osd1

- name: Set authorized key in ods2 node
  shell: ssh-copy-id -f -i /etc/ceph/ceph.pub root@ceph-osd2

- name: addding the monitor host in the cluster
  shell: ceph orch host add ceph-mon

- name: addding the osd1 host in the cluster
  shell: ceph orch host add ceph-osd1

- name: addding the osd2 host in the cluster
  shell: ceph orch host add ceph-osd2

- name: label the osd1 host
  command: ceph orch host label add ceph-osd1 osd

- name: label the osd2 host
  command: ceph orch host label add ceph-osd2 osd
