
- name: adding the monitor storage to the cluster
  shell: "sudo ceph orch daemon add osd ceph-mon:{{ vg }}/{{ lv }}"
  register: res_mon

- name: adding the osd1 storage to the cluster
  shell: "sudo ceph orch daemon add osd ceph-osd1:{{ vg }}/{{ lv }}"
  register: res_osd1

- name: adding the osd2 storage to the cluster
  shell: "sudo ceph orch daemon add osd ceph-osd2:{{ vg }}/{{ lv }}"
  register: res_osd2

- name: adding the mds storage to the cluster
  shell: "sudo ceph orch daemon add mds ceph-mds:{{ vg }}/{{ lv }}"
  register: res_mds

- name: fail the message with the messages
  fail:
    msg: "There is Error in addin the server"
  when: res_mon.rc == '22' or res_osd1.rc == '22' or res_osd2.rc == '22' or res_mds.rc =='22'
