
- name: set hostname to all deamons 
  hostname:
    name: "{{ ansible_hostname }}"

- name: identify the hosts in /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      10.204.68.12 ceph-admin
      10.204.68.14 ceph-mon
      10.204.68.15 ceph-osd1
      10.204.68.18 ceph-osd2
      10.204.68.22 ceph-mds
