
- name: set hostname to all deamons 
  hostname:
    name: "{{ ansible_hostname }}"

- name: identify the hosts in /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      10.204.68.5 ceph-admin
      10.204.68.6 ceph-mon
      10.204.68.9 ceph-osd1
      10.204.68.10 ceph-osd2
