
- hosts:
    - mon
    - osd1
    - osd2
  become: true

  vars:
    external_device: "{{ logicalvolume['external_device'] }}"
    partition_size: "{{ logicalvolume['partition_size'] }}GB"
    vg: "{{ logicalvolume['vg_name'] }}"
    partition_index: "{{ logicalvolume['external_device'] }}{{ logicalvolume['partition_index'] }}"
    lv: "{{ logicalvolume['lv_name'] }}"
    lvm_size: "{{ logicalvolume['lvm_size'] }}g"

  pre_tasks:
    - name: exit playbook, if the admin devices not exit
      fail:
        mag: "You must Define at least one admin node"
      when: admin not in groups

    - name: exit playbook, if the admin monitor and osd devices not exit
      fail:
        mag: "You must Define at least one monitor node"
      when: mons not in groups

    - name: exit playbook, if the admin monitor and osd devices not exit
      fail:
        mag: "You must Define at least one osd node"
      when: osds not in groups

    - import_tasks: create_lvm.yml
  
  tasks:
    - name: set_facts for the logical volumes
      set_fact:
        external_device: "{{ logicalvolume['external_device'] }}"
        partition_size: "{{ logicalvolume['partition_size'] }}GB"
        vg: "{{ logicalvolume['vg_name'] }}"
        partition_index: "{{ logicalvolume['external_device'] }}{{ logicalvolume['partition_index'] }}"
        lv: "{{ logicalvolume['lv_name'] }}"
        lvm_size: "{{ logicalvolume['lvm_size'] }}g"

    - import_tasks: create_lvm.yml

- hosts:
    - admin
    - mons
    - osd1
    - osd2
  pre_tasks:
    - import_role:
        name: ceph-prerun
      when: ansible_distribution == "Debian"
  tasks:
    - import_role:
        name: ceph-setup
