
- hosts:
    - mons
    - osd1
    - osd2
  become: true

  vars:
    external_device: "{{ logicalvolume['external_device'] }}"
    partition_size: "{{ logicalvolume['partition_size'] }}GB"
    vg: "{{ logicalvolume['vg_name'] }}"
    partition_index: "{{ logicalvolume['external_device'] }}{{ logicalvolume['partition_index'] }}"
    lv: "{{ logicalvolume['lv_name'] }}"
    lvm_size: "{{ logicalvolume['lvm_size'] }}g"

  pre_tasks:
    - name: check the lvs is exist or not
      command: lvs
      register: lvs

    - name: importing creating logical volume file
      import_tasks: create_lvm.yml
      when: lvs.stdout == ''
  
  tasks:
    - name: set_facts for the logical volumes
      set_fact:
        external_device: "{{ logicalvolume['external_device'] }}"
        partition_size: "{{ logicalvolume['partition_size'] }}GB"
        vg: "{{ logicalvolume['vg_name'] }}"
        partition_index: "{{ logicalvolume['external_device'] }}{{ logicalvolume['partition_index'] }}"
        lv: "{{ logicalvolume['lv_name'] }}"
        lvm_size: "{{ logicalvolume['lvm_size'] }}g"

    - import_tasks: create_lvm.yml

- hosts:
    - admin
    - mons
    - osd1
    - osd2
  pre_tasks:
    - import_role:
        name: ceph-prerun
  tasks:
    - import_role:
        name: ceph-setup
