
- hosts:
    - mons
    - osd1
    - osd2
  become: true

  vars:
    external_device: "{{ logicalvolume1['external_device'] }}"
    partition_size: "{{ logicalvolume1['partition_size'] }}GB"
    vg: "{{ logicalvolume1['vg_name'] }}"
    partition_index: "{{ logicalvolume1['external_device'] }}{{ logicalvolume1['partition_index'] }}"
    lv: "{{ logicalvolume1['lv_name'] }}"
    lvm_size: "{{ logicalvolume1['lvm_size'] }}g"

  pre_tasks:
    - name: check the lvs is exist or not
      command: lvs
      register: lvs

    - name: importing creating logical volume file
      import_tasks: create_lvm.yml
      when: lvs.stdout == ''
  
  tasks:
    - name: set_facts for the logical volumes
      set_fact:
        external_device: "{{ logicalvolume2['external_device'] }}"
        partition_size: "{{ logicalvolume2['partition_size'] }}GB"
        vg: "{{ logicalvolume2['vg_name'] }}"
        partition_index: "{{ logicalvolume2['external_device'] }}{{ logicalvolume2['partition_index'] }}"
        lv: "{{ logicalvolume2['lv_name'] }}"
        lvm_size: "{{ logicalvolume2['lvm_size'] }}g"
        
    - name: check if the lvs is create or not for storage
      shell: lvs | grep lv | wc -l
      register: nums_lvs
      
    - name: importing the create lvm task
      import_tasks: create_lvm.yml
      when: nums_lvs.stdout <= '1'

- hosts:
    - admin
    - mons
    - osd1
    - osd2
  pre_tasks:
    - import_role:
        name: ceph-prerun
  tasks:
    - import_role:
        name: ceph-setup
