
- hosts:
    - mons
    - osd1
    - osd2
    - mds
  become: true

  vars:
    external_device: "{{ logicalvolume['external_device'] }}"
    partition_size: "{{ logicalvolume['partition_size'] }}GB"
    vg: "{{ logicalvolume['vg_name'] }}"
    partition_index: "{{ logicalvolume['external_device'] }}{{ logicalvolume['partition_index'] }}"
    lv: "{{ logicalvolume['lv_name'] }}"
    lvm_size: "{{ logicalvolume['lvm_size'] }}g"
    times: "{{ logicalvolume['partition_index'] }}"

  pre_tasks:
    - name: check the lvs is exist or not
      command: lvs
      register: lvs

    - name: importing creating logical volume file
      import_tasks: create_lvm.yml
      when: lvs.stdout == ''

- hosts:
    - admin
    - mons
    - osd1
    - osd2
    - mds
  pre_tasks:
    - import_role:
        name: ceph-prerun
        
- hosts: admin
  become: true
  become_user: root

  tasks:
    - name: importing the setup_ceph.yml
      import_role:
        name: ceph-setup
        tasks_from: setup_ceph.yml

    - name: importing the nodes configuration  
      import_role: 
        name: node-configuration
