
- hosts:
    - mons
    - osd1
    - osd2
  become: true

  vars:
    external_device: "{{ logicalvolumes['logicalvolume1']['external_device'] }}"
    partition_size: "{{ logicalvolumes['logicalvolume1']['partition_size'] }}GB"
    vg: "{{ logicalvolumes['logicalvolume1']['vg_name'] }}"
    partition_index: "{{ logicalvolumes['logicalvolume1']['external_device'] }}{{ logicalvolumes['logicalvolume1']['partition_index'] }}"
    lv: "{{ logicalvolumes['logicalvolume1']['lv_name'] }}"
    lvm_size: "{{ logicalvolumes['logicalvolume1']['lvm_size'] }}g"
    times: "{{ logicalvolumes['logicalvolume1']['partition_index'] }}"

  pre_tasks:
    - name: check the lvs is exist or not
      command: lvs
      register: lvs
      
    - name: create partition
      parted:
        device: "{{ item.external_device }}"
        number: "{{ item.times }}"
        flags: [ lvm ]
        state: present
        part_start: "{{ item.partition_size }}"
      with_items: "{{ logicalvolumes }}"

    - name: importing creating logical volume file
      import_tasks: create_lvm.yml
      when: lvs.stdout == ''
  tasks:
    - name: set_facts for the logical volumes
      set_fact:
        external_device: "{{ logicalvolumes['logicalvolume2']['external_device'] }}"
        partition_size: "{{ logicalvolumes['logicalvolume2']['partition_size'] }}GB"
        vg: "{{ logicalvolumes['logicalvolume2']['vg_name'] }}"
        partition_index: "{{ logicalvolumes['logicalvolume2']['external_device'] }}{{ logicalvolumes['logicalvolume2']['partition_index'] }}"
        lv: "{{ logicalvolumes['logicalvolume2']['lv_name'] }}"
        lvm_size: "{{ logicalvolumes['logicalvolume2']['lvm_size'] }}g"
        times: "{{ logicalvolumes['logicalvolume2']['partition_index'] }}"

    - debug: msg="{{ external_device}} {{partition_size}}  {{vg}} {{partition_index}} {{lvm_size}} {{times }}"
    - name: check if the lvs is create or not for storage
      shell: lvs | grep lv | wc -l
      register: nums_lvs
      
    - name: importing the create lvm task
      import_tasks: create_lvm.yml
      when: nums_lvs.stdout <= '1'

- hosts:
    - admin
    - mons
    - osd1
    - osd2
  pre_tasks:
    - import_role:
        name: ceph-prerun
        
- hosts: admin
  become: true
  become_user: root
  tasks:
    - name: importing the setup_ceph.yml
      import_role:
        name: ceph-setup
        tasks_from: setup_ceph.yml
      become: true
      become_user: root

    - name: importing theaddingnds      
      import_role: 
        name: adding-nds
      become: true
      become_user: root