
- hosts:
    - mons
    - osd1
    - osd2
    - mds
  become: true

  vars:
    external_device: "{{ logicalvolume1['external_device'] }}"
    partition_size: "{{ logicalvolume1['partition_size'] }}GB"
    vg: "{{ logicalvolume1['vg_name'] }}"
    partition_index: "{{ logicalvolume1['external_device'] }}{{ logicalvolume1['partition_index'] }}"
    lv: "{{ logicalvolume1['lv_name'] }}"
    lvm_size: "{{ logicalvolume1['lvm_size'] }}g"
    times: "{{ logicalvolume1['partition_index'] }}"

  pre_tasks:
    - name: check the lvs is exist or not
      command: lvs
      register: lvs
      
    - name: create partition
      parted:
        device: "{{ item.external_device }}"
        number: "{{ item.times }}"
        flags: [ lvm ]
        state: present
        part_start: "{{ item.partition_size }}"
      with_items: "{{ logicalvolumes }}"

    - name: importing creating logical volume file
      import_tasks: create_lvm.yml
      when: lvs.stdout == ''
  tasks:
    - name: set_facts for the logical volumes
      set_fact:
        external_device: "{{ logicalvolume2['external_device'] }}"
        partition_size: "{{ logicalvolume2['partition_size'] }}GB"
        vg: "{{ logicalvolume2['vg_name'] }}"
        partition_index: "{{ logicalvolume2['external_device'] }}{{ logicalvolume2['partition_index'] }}"
        lv: "{{ logicalvolume2['lv_name'] }}"
        lvm_size: "{{ logicalvolume2['lvm_size'] }}g"
        times: "{{ logicalvolume2['partition_index'] }}"

    - debug: msg="{{ external_device}} {{partition_size}}  {{vg}} {{partition_index}} {{lvm_size}} {{times }}"
    - name: check if the lvs is create or not for storage
      shell: lvs | grep lv | wc -l
      register: nums_lvs
      
    - name: importing the create lvm task
      import_tasks: create_lvm.yml
      when: nums_lvs.stdout <= '1'

- hosts:
    - admin
    - mons
    - osd1
    - osd2
    - mds
  pre_tasks:
    - import_role:
        name: ceph-prerun
        
- hosts: admin
  become: true
  become_user: root
  vars:
    external_device: "{{ logicalvolume2['external_device'] }}"
    partition_size: "{{ logicalvolume2['partition_size'] }}GB"
    vg: "{{ logicalvolume2['vg_name'] }}"
    partition_index: "{{ logicalvolume2['external_device'] }}{{ logicalvolume2['partition_index'] }}"
    lv: "{{ logicalvolume2['lv_name'] }}"
    lvm_size: "{{ logicalvolume2['lvm_size'] }}g"

  tasks:
    - name: importing the setup_ceph.yml
      import_role:
        name: ceph-setup
        tasks_from: setup_ceph.yml
      become: true
      become_user: root

    - name: importing theaddingnds      
      import_role: 
        name: adding-nds
      become: true
      become_user: root